### ISSUE TITLE
helia-5.5 missing install rules in makefile for .mo languages files

### ISSUE THREAD

**Issue by martinkg** [vl-nix/Helia#11]
Hi,
tried to compile helia-5.5 on fedora, make doesn't create any .mo languages file.

helia-5.1.1 works perfect.

Regards
Martin

**Comment by vl-nix** [comment]
> languages

Ver. 5.4:
gettex package is used ( po/*.po --> locale/.../*.mo )

Ver. 5.5:
( languages ) is included in the program ( po/*.po --> src/lang.c )

**Comment by martinkg** [comment]
On Fedora 29

```
tar xfz helia-5.5.tar.gz; cd Helia-5.5
make
find . -name "*.mo" -print
```

no .mo files are created

**Comment by vl-nix** [comment]
> no .mo files are created

[Latest release  5.6.1](https://github.com/vl-nix/Helia/releases/latest)

Gettex package is used
* not accessible possibility to choose languages in the program
