### ISSUE TITLE
Can this run on an android device?

### ISSUE THREAD

**Issue by zkjmyy** [vl-nix/Helia#13]
Can this run on an android device? Can you give me some suggestions? Such as compilation.

**Comment by vl-nix** [comment]
> Can this run on an android device?

I don't know.

This project is written for Linux in pure C, mainly for desktops. There is no code for Android in Java or Kotlin.

**Comment by zkjmyy** [comment]
This runs on a linux device, do I need an external antenna? Such as USB antenna. I am an Android developer, and I want to research to see if it can be ported to Android devices.

**Comment by vl-nix** [comment]
Usually, there are two ways for a computer to connect a DVB device - DVB USB and DVB PCI.

First, you need to make sure that the DVB device is supported in the Linux kernel ( for example, the list for DVB-T2 USB Devices is here ) - https://www.linuxtv.org/wiki/index.php/DVB-T2_USB_Devices

**Comment by vl-nix** [comment]
Connection examples:

Computer -> DVB-T / T2 -> Digital Terrestrial Antenna

Computer -> DVB-S/S2 -> Digital Satellite Dish

Computer -> DVB-C/C2 -> Digital Cable TV
