### ISSUE TITLE
undefined macro: LT_PACKAGE_VERSION

### ISSUE THREAD

**Issue by ua0lnj** [vl-nix/Helia#2]
Привет, лень разбираться самому, хотел собрать на федоре 27, получил:

root@ua0lnjhome Helia]# ./autogen.sh
rm -f data/helia.desktop
rm -f helia src/*.o data/*.o data/*.c po/*.pot po/*.po~
rm -fr locale
m4/ax_cxx_compile_stdcxx_11.m4
m4/ax_check_compile_flag.m4
m4/ax_compiler_vendor.m4
m4/appstream-xml.m4
m4/ax_require_defined.m4
m4/introspection.m4
m4/ax_compiler_flags_cxxflags.m4
Makefile.am
configure.ac
m4/gsettings.m4
m4/libtool.m4
m4/pkg.m4
m4/ax_check_link_flag.m4
m4/ax_append_flag.m4
m4/intltool.m4
m4/ax_append_compile_flags.m4
m4/vapigen.m4
m4/glib-gettext.m4
m4/
m4/Makefile.am
Set Ver.  3.0.0
autoreconf: Entering directory `.'
autoreconf: running: autopoint --force
Copying file ABOUT-NLS
Creating directory build-aux
Copying file build-aux/config.rpath
Copying file m4/codeset.m4
Copying file m4/extern-inline.m4
Copying file m4/fcntl-o.m4
Copying file m4/gettext.m4
Copying file m4/glibc2.m4
Copying file m4/glibc21.m4
Copying file m4/iconv.m4
Copying file m4/intdiv0.m4
Copying file m4/intl.m4
Copying file m4/intldir.m4
Copying file m4/intlmacosx.m4
Copying file m4/intmax.m4
Copying file m4/inttypes-pri.m4
Copying file m4/inttypes_h.m4
Copying file m4/lcmessage.m4
Copying file m4/lib-ld.m4
Copying file m4/lib-link.m4
Copying file m4/lib-prefix.m4
Copying file m4/lock.m4
Copying file m4/longlong.m4
Copying file m4/nls.m4
Copying file m4/po.m4
Copying file m4/printf-posix.m4
Copying file m4/progtest.m4
Copying file m4/size_max.m4
Copying file m4/stdint_h.m4
Copying file m4/threadlib.m4
Copying file m4/uintmax_t.m4
Copying file m4/visibility.m4
Copying file m4/wchar_t.m4
Copying file m4/wint_t.m4
Copying file m4/xsize.m4
Copying file po/Makefile.in.in
Copying file po/Makevars.template
Copying file po/Rules-quot
Copying file po/boldquot.sed
Copying file po/en@boldquot.header
Copying file po/en@quot.header
Copying file po/insert-header.sin
Copying file po/quot.sed
Copying file po/remove-potcdate.sin
autoreconf: running: aclocal --force 
configure.ac:98: error: m4_defn: undefined macro: LT_PACKAGE_VERSION
m4/libtool.m4:40: LT_PREREQ is expanded from...
configure.ac:98: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1

**Comment by vl-nix** [comment]
Need to install the package autoconf-archive.

**Comment by ua0lnj** [comment]
Was installed.
No result.
Пока больше некогда, потом как-нибудь попробую разобраться....

**Comment by vl-nix** [comment]
Install autopoint libtool-bin

**Comment by vl-nix** [comment]
Section - Initialize Libtool - disabled ( LT_PREREQ; LT_INIT; **LT_PACKAGE_VERSION** ... ).
It should now be built without any additional packages ( autopoint, autoconf-archive ).

Раздел - Initialize Libtool - отключен. 
Теперь должно быть собрано без каких-либо дополнительных пакетов.
