### ISSUE TITLE
Czech localization file to commit

### ISSUE THREAD

**Issue by pafri** [vl-nix/Helia#7]
Hi,
I've used "nl" file also check, if the header is fine. Zipped.
[helia_cs_CZ.tar.gz](https://github.com/vl-nix/Helia/files/2475128/helia_cs_CZ.tar.gz)

**Comment by vl-nix** [comment]
Thanks. 

If possible, add Pull:

1. git clone git@github.com:vl-nix/Helia.git ( or git clone https://github.com/vl-nix/Helia.git )
3. cp helia_cs_CZ.po Helia/po/cs_CZ.po
4. git add .
5. git commit -m "Czech localization"
6. git push

If not possible ( not enough time ... )... I will add translation.
