### ISSUE TITLE
Support of multifrontend device

### ISSUE THREAD

**Issue by ua0lnj** [vl-nix/Helia#9]
Astrometa dvbt/t2/c usb:

adapter  0 
frontend 0 

DVBv5:  Ok
DVB device:  Realtek RTL2832 (DVB-T)
DVB-T  ( 3 )
API Version:  5.11
Flag:  O_RDWR

adapter  0 
frontend 1 

DVBv5:  Ok
DVB device:  Panasonic MN88473
DVB-T  ( 3 )
API Version:  5.11
Flag:  O_RDWR

** (helia:6000): CRITICAL **: 15:19:39.967: scan_msg_err:: Устройство «/dev/dvb/adapter0/dvr1» не существует. (gstdvbsrc.c(1794): gst_dvbsrc_open_dvr (): /GstPipeline:pipeline_scan/GstDvbSrc:dvbsrc0)

[root@ua0lnjhome adapter0]# ls /dev/dvb/adapter0
demux0  dvr0  frontend0  frontend1  net0

See:
https://www.linuxtv.org/wiki/index.php/Astrometa_DVB-T2
https://www.vdr-portal.de/forum/index.php?thread/132190-patch-f%C3%BCr-multi-frontend-devices/
https://cgit.kde.org/kaffeine.git/commit/?id=6b6a936a0dbf5951b6377554d0400220a5602074

**Comment by vl-nix** [comment]
>  Устройство «/dev/dvb/adapter0/dvr1» не существует. (gstdvbsrc.c(1794): gst_dvbsrc_open_dvr ()

>  ls /dev/dvb/adapter0  -  demux0 dvr0 frontend0 frontend1 net0


Test Gstreamer - Support of multifrontend device

# Download

	https://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-1.14.4.tar.xz
or 
	wget https://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-1.14.4.tar.xz

tar -xvf gst-plugins-bad-1.14.4.tar.xz

cd gst-plugins-bad-1.14.4


# Edit gstdvbsrc.c - for support of multifrontend device

edit sys/dvb/gstdvbsrc.c ( gst_dvbsrc_open_dvr () )

1785:   dvr_dev = g_strdup_printf ("/dev/dvb/adapter%d/dvr%d",
1786:      object->adapter_number, object->frontend_number);

chang
1786:      object->adapter_number, object->adapter_number);


# Build

sh configure

cd gst-libs/gst/codecparsers
make

cd ../../../gst-libs/gst/mpegts
make

cd ../../../sys/dvb
make

cd ../../../


# Path install

path=`gst-inspect-1.0 dvbsrc | grep Filename | sed 's|^.*/usr|/usr|;s|libgstdvb.so||'`

sudo cp sys/dvb/.libs/libgstdvb.so $path

**Comment by vl-nix** [comment]
Patchfile ( for sys/dvb/gstdvbsrc.c )

diff --git a/sys/dvb/gstdvbsrc.c b/sys/dvb/gstdvbsrc.c
index d9bee26..a7959fc 100644
--- a/sys/dvb/gstdvbsrc.c
+++ b/sys/dvb/gstdvbsrc.c
@@ -1784,6 +1784,12 @@ gst_dvbsrc_open_dvr (GstDvbSrc * object)
 
   dvr_dev = g_strdup_printf ("/dev/dvb/adapter%d/dvr%d",
       object->adapter_number, object->frontend_number);
\+
\+  if ( !g_file_test ( dvr_dev, G_FILE_TEST_EXISTS ) )
\+  {
\+	g_free (dvr_dev);
\+	dvr_dev = g_strdup_printf ("/dev/dvb/adapter%d/dvr%d", adapter_number, 0);
\+  }
   GST_INFO_OBJECT (object, "Using DVR device: %s", dvr_dev);
 
   /* open DVR */

**Comment by vl-nix** [comment]
Patchfile - [gst-multifrontend.diff.txt](https://github.com/vl-nix/Helia/files/2683730/gst-multifrontend.diff.txt)

diff --git a/sys/dvb/gstdvbsrc.c b/sys/dvb/gstdvbsrc.c
index d9bee26..3af3bcc 100644
--- a/sys/dvb/gstdvbsrc.c
+++ b/sys/dvb/gstdvbsrc.c
@@ -1784,6 +1784,13 @@ gst_dvbsrc_open_dvr (GstDvbSrc * object)
 
   dvr_dev = g_strdup_printf ("/dev/dvb/adapter%d/dvr%d",
       object->adapter_number, object->frontend_number);
\+
\+  if ( !g_file_test ( dvr_dev, G_FILE_TEST_EXISTS ) )
\+  {
\+    g_free (dvr_dev);
\+    dvr_dev = g_strdup_printf ("/dev/dvb/adapter%d/dvr%d", adapter_number, 0);
\+  }
\+
   GST_INFO_OBJECT (object, "Using DVR device: %s", dvr_dev);
 
   /* open DVR */
@@ -2770,6 +2777,12 @@ gst_dvbsrc_set_pes_filters (GstDvbSrc * object)
   gchar *demux_dev = g_strdup_printf ("/dev/dvb/adapter%d/demux%d",
       object->adapter_number, object->frontend_number);
 
\+  if ( !g_file_test ( demux_dev, G_FILE_TEST_EXISTS ) )
\+  {
\+    g_free (demux_dev);
\+    demux_dev = g_strdup_printf ("/dev/dvb/adapter%d/demux%d", adapter_number, 0);
\+  }
\+
   GST_INFO_OBJECT (object, "Setting PES filter");
 
   /* Set common params for all filters */

**Comment by ua0lnj** [comment]
Я думаю не правильно выбирается delivery system.
Иногда
adapter  0 
frontend 1 

DVBv5:  Ok
DVB device:  Panasonic MN88473
DVB-C-A  ( 1 )
API Version:  5.11
Flag:  O_RDWR

Иногда 
adapter  0 
frontend 1 

DVBv5:  Ok
DVB device:  Panasonic MN88473
DVB-T  ( 3 )
API Version:  5.11
Flag:  O_RDWR

При поиске DVB-T2 ошибка 
kernel: usb 1-1: DVB: adapter 0 frontend 1 symbol rate 0 out of range (1000000..7200000)
При этом если задать в DVB-C параметр symbolrate, ошибки нет, но ничего не принимает.

При выставлении streamid != 0 ошибка
** (helia:18283): CRITICAL **: 23:26:34.706: scan_msg_err:: Ошибка GStreamer: не удалось изменить состояние и некоторым элементам не удалось поместить правильное сообщение о причиной ошибки. (gstbasesrc.c(3452): gst_base_src_start (): /GstPipeline:pipeline_scan/GstDvbSrc:dvbsrc0:
Failed to start)

Т.е. похоже, что всегда выбирает DVB-C.
Проверить DVB-C не могу.

**Comment by vl-nix** [comment]
Astrometa dvbt/t2/c usb - демодуляторы:

1. The RTL2832 is a high-performance DVB-T COFDM demodulator that supports a USB 2.0 interface. Support  ISDB-T ( SBTVD-T ) 1-Seg,  FM/DAB/DAB+.

2. The MN88472 is a DVB-T/DVB-T2/DVB-C demodulator chip manufactured by Panasonic.

1. Realtek RTL2832  -  adapter 0 frontend 0:
	1. постоянно  DVB-T

2. Panasonic MN88473   -  adapter 0 frontend 1  -  может быть:
	1. DVB-T
	2. DVB-T2
	3. DVB-C

Можно предположить: теоретически, в зависимости от типа сигнала, адаптер будет самостоятельно устанавливать тип DVB-T или DVB-C... но ошибка указывает, что по умолчанию выбирается DVB-C:

> kernel: usb 1-1: DVB: adapter 0 frontend 1 symbol rate 0 out of range (1000000..7200000)
При этом если задать в DVB-C параметр symbolrate, ошибки нет, но ничего не принимает.

В связи с этим, в программу внесена возможность - вручную указать тип модулятора.

Вкладка -> Сканер -> Delivery manually

**Comment by ua0lnj** [comment]
Работает!
It's work :)
